//Using the dom to access a specific element on the page, in this case, out picture of the eightball and storing it in a variable called eightballImage:
const eightballImage = document.getElementById('eightball-image');

//MDN code snippet as reference:
//document.getElementById("myBtn").addEventListener("click", displayDate);

//variable.addEventListener("click", )



//Using a prompt, ask the the user's name and then store that name in a variable called userName
const userName = prompt("Hello seeker of wisdom, what is your name?");

//Alert that then takes the newly created userName variable and injects that into the string to say "Hello ${userName}. I can see you have questions for me..."
alert(`Hello ${userName}. I can see you have questions for me...`);


//Funtion to do everything we want the eightball to do when we click it:

//We've created a new arrow function and called it "clickBall"
const clickBall = () => {
  //Step one, once ball clicked a prompt comes up and asks the user for their question:
  prompt("Ask me a yes no question and I shall reveal your fate.")
  //User clicks enter and the answer will appear in the empty p tag underneath the eightball image after all this jazzy maths:

  //Generates random number in between 1 and 8:
  let randomNumber = Math.floor(Math.random() * 8);

  //Creating a variable of an empty string for the answer to inject into:
  let eightBall = "";

  //Switch statement that assigns a different response depending on the outcome of randomNumber:
  switch (randomNumber) {
    case 0:
      eightBall = "It is certain.";
      break;
    case 1:
      eightBall = "It is decidedly so.";
      break;
    case 2: 
      eightBall = "Reply hazy try again...";
      break;
    case 3:
      eightBall = "Cannot predict now, ask me another question.";
      break;
    case 4:
      eightBall = "Do not count on it.";
      break;
    case 5:
      eightBall = "My sources say no.";
      break;
    case 6:
      eightBall = "Outlook not so good.";
      break;
    case 7:
      eightBall = "Signs point to yes!"
      break;
  }

  //Using the dom to access a specific element on the page, in this case, the p tag underneath the eightball image:
  const pTagResponse = document.getElementById('answer');

  //Using the javascript innerHTML method, we have replaced the inner html of the p tag with the text generated by the outcome of the random match switch statement.
  pTagResponse.innerHTML = eightBall;

};


//Added an event listener (a type of tracker looking out for any user interaction) to the eightballImage. Specifically it's listening out for a click and when that happens it calls the clickBall function. 
eightballImage.addEventListener("click", clickBall())


